language: cpp
compiler:
    - g++
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
install:
  - sudo apt-get install -qq gcc-4.9
  - export CXX="g++-4.9"
before_script:
    - mkdir build/
    - cd build/
    - cmake ../
script:
    - make